language: python
python:
- '2.7'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate
- sam package --template-file template.yaml --s3-bucket $LAMBDAS_BUCKET --output-template-file
  packaged.yaml
before_install:
- openssl aes-256-cbc -K $encrypted_840430a43af2_key -iv $encrypted_840430a43af2_iv -in made2591.pem.enc -out made2591.pem -d
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --stack-name lambdas --capabilities
    CAPABILITY_IAM
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: MrMLN9RmKHEmPb7+XEx/YL01O3vE8yKwL9da3/FSs2QP7r97+gNoMk/pXV5INi+4D3o+hOS7kGe/yktsqhjd2fAAS+rA2fXn3j6/YiyLMQ8zZY0kmMOxPKm3gFp2YtJ4kB6ImHQ1HK+fft4S4baEGFUuBeSbTjzJ9Z3XexEi6CyXm5FK/0Z9zYYu5fWCToY5u3ksW1l7rwwNfyaOzJh98l1886LNYFlknquCK3E0IL1bHV0O+88V51T+UMCKq3y6DdmSF+48MVSpDXyRhOSmlfcI5VPRp5FzetonklBCwYuWlk9S9UrXGurEIzPDlwYDDwxofOaHnVkVQIMRwCwvMVGCjCp6tvlewwytIQIu0qc4wBjakpZaLNJYV9O6Ktl1xxOkCPUa9hizP43hbQNo1zk2xOTjRxmjAj21OJpygPT65rRL/TaDMgc7WlaIJr4rvhdHPOIXLmcbi5zr5eofjTJSEgD1W6rzSG/3XA/XESVH4M9fkbQaorMcbBp1tVDE8xBdr9lKtnwXjBfOl1DvB696iIkgnY562tcjU6ZDUJKTHFXjGt7x4XNJ0wq42teNXD9Ep7sY1MKfHkqLvWelgEXOb6BX1BoywMlAnqIva2bLh+YJ9Jgfqt71HQGrjQ2Cle0LU2ueWgvtfNL5RkASbZRJIUV5pSkJFx5NXG3VVoo=
  - secure: f/EgEGrrZfkwTtojeyYOEFlwa73qNRWAcusYmVciU9j3/PqRiVRQJXMRP3uGK2QIzFzYXVp+FxBXkAhZvHnDjp40pS58/hLMm3b4d85aNXE+gUvtP4slhgTtOtZSUnOkmFaxoUNlHhiNtsIg3XgN/xyubRSRa/gkBnnFH8K2WXH8qWVR1qT1hr4ebsBZzzAuWfoD8toMGqWXxj3z9R218tDjY1q+6uYzAO79rO4s5H5SJ3+S656p9SoTeLur70RTqO1qHLue/OvXaqubkiRHdbCq3r/VEA++tZux7/gX0lGTAv4X+TnBwwdPsEG8p13XO4fT2OK6jl8IDRZ8mLAxW4R0Sd4IocdEPCftoQUCs8Ae8ebYFelXnP5wqdljPksotplI5lI1eK/JWoABWi0L2hz+o7doRxPAtU/mNzCHjjgsVDHXEGwFc4egPD/rUz5iRjVob1Wc4zFV2x0dfpH0qwABwK2njzOBfHI0pQSR5T5ifKArJHvfVH49/YqZ+CDLjsrG8uRd17ITcqyIwzF6RlGxJ15zWUPrueYYkvu50dw/irKUIhwgLijPPrwjx5lx6VURWt8QelmN+C0RuYRv+QlAxuSolHbNpnpCpFJL8b7NgiLML4GOu2qhIDe0hcGHRXwFajiTAtD5gQc0c9RG3n5vQgTwtrXrBYm70OTjd34=
  - secure: rCxssT45Af3Vtgq+tFkvC5qHflIgcasvS6tILF2+xcq8Q0MFuk7pOgnX2LPISgypsvI4Bmr1NG+eYEJVOW66sJ/lhet1z+9+n195tfyJsT0CgCUTMOqglEXPzT95iDhSpxZvwu0XEZSAEE5J0VWVXMkRCVzD092160dvHjVjg821/DC8Yo0HSR9Q1NMwHA2q6b8TR/m+EreTNlGm3GA+bQgctXZnbN4YmqEGpG+rr7Woio/7b9o/FOPNp3WF0qh5veCGKfrctsmdySTIJLSMRq1j1H6zIbh7nTjOjiWB+ys4vQhigu8kK5ggM1tJ7fKXRdhawSEXsqXFJ5+r/bs+2JYhwKTFJgIHxIyp/90KvGtlNypVICCtbvvolAihepDyTTD4FcQkvKX603fV2huC28HuxOl+0b81cbjJX5r1UhV9Uoeu5AC3PBTwP5u8VfWowqvxbPkoi/DcCyZXnS/RGOogqgbwS8q4V81QFTlk4TUNokFEB6RG1FcYYJp8LXkvf2KliD68I4ULY+AbWXEyjNGixCA0WhAEs/p4Ox8f9eyUAXPlMU75Ni+4xI5fvic9um50Iq5CBFVd+pb2Fe0YC2u6SaxvM3Vqf6MDIKKDG5HuvcRCaLXA0VPvV1pIdBEFQpUr9bUh+Ql5G4mgVP4BSLvgI+RohUKZ5U8LkBBAwOE=
  - secure: "FVfKm5nRBbk0Pe8zXG7cgE/kxjPZDlKjZhywO/H9ULPdTJ1OnBYN2iH5x6cb/b56SCK3LWO8u8NtAfOaiYR2PAq/8tmfX1YLQIfiVtjwytAEP99H2+hBs1ta9kHhs+L6Mcd7/fl1lhzjq+Iw1NwXLqoNlPyKB13yZefDMd/mRnXOnWMVDfVia40C+ljozyngBvoUnvRY4aX5iqGc1LPLa4iTO/DQbGBcwbFGEUYE2vRqZj/nSZvq+k3dhBjJnahK85u2CknEkKHDGFgdjta8/7PM1ujN69bQIh+0YWjued2KHLrj/USZcYFH8WmwqOiBpAb9cEMLLVnlUpRqYtNmCOe7PG0BDh1bc/oqn0+VZRTzdYIYPV+o3+n4KyG8XAJkhpa09IvMkdzTqo2a6CtMyEi4lGU2mo0U8aLVr4axNga7q9iENAN0cWN/UwTsxz6owKmdRzNquyFszfplqjHNJI2teTKnNwqKTS/qPJaUWsdIVRx7GdJzqV/zSfxIIPIxPLxMcLGJF7Sp/LDoOTGzhOolDKs8U4uw/fPAMsl5iFHZOAMrwvZ15wtkHBer4zIzJFWgkAKY57/9HZUNUudrZkRfyPQDutJiTjEPxm3KgunhUTeRDgoaRmabuTEYnCqfOM1vXxBzMW32gE6+1rxKnWpH/AfN3mgklU0YKS5cPB4="