AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambdas

Resources:

  LambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/authorizer/index.handler
      Environment:
        Variables:
          TOKEN_ISSUER: $TOKEN_ISSUER
          JWKS_URI: $JWKS_URI
          AUDIENCE: $AUDIENCE
      Timeout: 30
      Runtime: nodejs10.x

  TestLambdaAuthorizerPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ApiGateway
      - LambdaAuthorizer
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaAuthorizer
      Principal: apigateway.amazonaws.com

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: ApiGatewayAuthorizer
        Authorizers:
          ApiGatewayAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt LambdaAuthorizer.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 3600

  PythonBoilerplate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/python-boilerplate/
      Handler: lambda.handler
      Timeout: 300
      Runtime: python3.6
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              !Ref ApiGateway
            Path: /
            Method: post
